import os
from time import sleep
os.system('ps aux | grep subdomains.py')
N=10   # number of subdomains 
os.system('python create_dataset_files.py --dataset-path /users2/libre/datasets/ --subdomain /users/local/clusters_imagenet/'+str(N)+'clusters.npy --fast-create-dataset')
os.system('python main.py --dataset-path /users2/libre/datasets/ --few-shot-shots 5 --few-shot-ways 5 --few-shot-queries 15 --training-dataset metadataset_imagenet_4 --validation-dataset metadataset_cub_validation --test-dataset metadataset_cub_test --epochs 20 --lr 0.05 --few-shot --few-shot-unbalanced-queries --load-backbone /users2/libre/clusters/clusters --save-classifier /users2/libre/raphael/finetune_cubc4_classifier.pt  --backbone resnet12 --freeze-backbone --force-train')# --wandb raflaf --wandbProjectName brain-train' )
os.system('python main.py --dataset-path /users2/libre/datasets/ --few-shot-shots 5 --few-shot-ways 5 --few-shot-queries 15 --training-dataset metadataset_imagenet_4 --validation-dataset metadataset_cub_validation --test-dataset metadataset_cub_test --epochs 50 --lr 0.0001 --few-shot --few-shot-unbalanced-queries --load-backbone /users2/libre/clusters/clusters --save-backbone /users2/libre/raphael/finetune_cubc4.pt --save-features-prefix /users2/libre/raphael/finetuned_cubc4 --load-classifier /users2/libre/raphael/finetune_cubc4_classifier.pt  --backbone resnet12')# --wandb raflaf --wandbProjectName brain-train' )
#for i in range(N):
#    os.system('python main.py --dataset-path /users2/libre/datasets/ --few-shot-shots 5 --few-shot-ways 5 --few-shot-queries 15 --training-dataset metadataset_imagenet_cluster_train_'+str(i)+' --validation-dataset metadataset_aircraft_validation --test-dataset metadataset_vgg_flower_test --epochs 200 --lr 0.1 --cosine --few-shot --few-shot-unbalanced-queries  --save-backbone /users/local/r21lafar/models/randomlargeclusters'+str(i)+' --backbone resnet12')# --wandb raflaf --wandbProjectName brain-train' )
#    sleep(3)  # time to exit process